# Generated by Django 5.1.5 on 2025-06-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citoyenprofile',
            old_name='prénom',
            new_name='prenom',
        ),
    ]
