# Generated by Django 5.1.5 on 2025-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_rename_prénom_citoyenprofile_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationprofile',
            name='feedback',
        ),
        migrations.AddField(
            model_name='associationprofile',
            name='fefeedback',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='citoyenprofile',
            name='feedback',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
