# Generated by Django 5.1.5 on 2025-06-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_remove_associationprofile_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associationprofile',
            old_name='fefeedback',
            new_name='feedback',
        ),
    ]
