# Generated by Django 5.1.5 on 2025-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_rename_fefeedback_associationprofile_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationprofile',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citoyenprofile',
            name='album_photos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citoyenprofile',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
