# Generated by Django 5.1.5 on 2025-06-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_alter_associationprofile_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationprofile',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
