# Generated by Django 5.1.5 on 2025-06-26 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_remove_annonce_association_annonce_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
    ]
