# Generated by Django 5.1.5 on 2025-06-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_alter_annonce_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='citoyen',
        ),
    ]
