# Generated by Django 5.1.5 on 2025-06-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_rename_id_user_annonce_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
