# Generated by Django 5.1.5 on 2025-06-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0010_alter_candidature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
