# Generated by Django 5.1.5 on 2025-06-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_alter_candidature_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='id_user',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
