# Generated by Django 5.1.5 on 2025-06-28 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0012_candidature_id_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='id_user',
        ),
        migrations.AddField(
            model_name='annonce',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='login_app.associationprofile', verbose_name='Association'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='citoyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.citoyenprofile'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='login_app.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='type',
            field=models.CharField(choices=[('EVENEMENT', 'Évènement'), ('DON', 'Don'), ('APPEL_BENEVOLAT', 'Appel au bénévolat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='associationprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citoyenprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
